---
abstract: 'Catmandu modules for working with solr endpoints'
author:
  - 'Nicolas Steenlant, C<< nicolas.steenlant at ugent.be >>'
build_requires:
  Module::Build: 0.3601
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Solr
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  CQL::Parser: 1.12
  Catmandu: 0.7
  Moo: 1.00
  WebService::Solr: 0.16
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Solr/issues
  homepage: https://github.com/LibreCat/Catmandu-Solr
  repository: https://github.com/LibreCat/Catmandu-Solr.git
version: 0.0207
x_contributors:
  - 'Jakob Voss <voss@gbv.de>'
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
  - 'njfranck <njfranck@ca20c521.ugent.be>'
